[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/fetch-meta"
  to = "/.netlify/functions/fetch-meta"
  status = 200

[[redirects]]
  from = "/generate"
  to = "/.netlify/functions/generate"
  status = 200
